### ISSUE TITLE
如何动态配置gradle插件是否启动

### ISSUE THREAD

**Issue by protectedMan** [leavesC/ASM_Transform#4]

**Comment by protectedMan** [comment]
实现debug包 不启用apply plugin: DoubleClickPlugin，release包启用
有什么好方法呢？

**Comment by leavesCZY** [comment]
我没这样试过，你可以试着在 DoubleClickPlugin 中获取 variant，根据 variant 类型来决定是否开启 doubleClick 的逻辑

**Comment by protectedMan** [comment]
> 我没这样试过，你可以试着在 DoubleClickPlugin 中获取 variant，根据 variant 类型来决定是否开启 doubleClick 的逻辑

`
class DoubleClickPlugin : Plugin<Project> {

    override fun apply(project: Project) {
       var variant= project.gradle.startParameter.taskRequests.toString();
        print("config.enabled:"+project.gradle.startParameter.taskRequests.toString())
        if(variant.contains("assemble",true) || variant.contains("Release",true)){
            val appExtension: AppExtension = project.extensions.getByType()
            appExtension.registerTransform(DoubleClickTransform(DoubleClickConfig()))
        }
    }
}
`
